Update linter.demo.yml

diff --git a/.github/workflows/linter.demo.yml b/.github/workflows/linter.demo.yml
--- a/.github/workflows/linter.demo.yml
+++ b/.github/workflows/linter.demo.yml
@@ -1,11 +1,9 @@
 name: Flake8 Linter
 
 on: [push]
-
-  # pull_request:
-  #   branches:
-  #     - master
-
+ # pull_request:
+  #  branches:
+   #   - master
 
 jobs:
   lint:
@@ -31,22 +29,21 @@ jobs:
           cat flake8-output.txt >> append.txt
           mv append.txt flake8-output.txt
           
-      - name: Check Output Content and Upload flake8 results
-        id: check_output_content
-        run: |
-          if [ $(stat -c %s "$GITHUB_WORKSPACE/flake8-output.txt") -gt 2 ]; then
-            echo "flake8-output.txt is not empty. Uploading results..."
-            mv $GITHUB_WORKSPACE/flake8-output.txt $GITHUB_WORKSPACE/flake8-results.txt
-            echo "upload_results=true" >> $GITHUB_ENV
-            exit 1
-          else
-            echo "flake8-output.txt is empty. No results to upload."
-            echo "upload_results=false" >> $GITHUB_ENV
-          fi
-          
       - name: Upload flake8 results
+        id: upload_results
         uses: actions/upload-artifact@v3
-        if: env.upload_results == 'true'
         with:
           name: flake8-results
-          path: ${{ github.workspace }}/flake8-results.txt  
+          path: ${{ github.workspace }}/flake8-output.txt
+          
+      - name: Check Output Content and Fail Test
+        run: |
+          if [stat -c "$GITHUB_WORKSPACE/flake8-output.txt" -gt 1]; then
+            echo "Error: flake8-output.txt is not empty."
+          else
+            echo "flake8-output.txt is empty."
+          fi
+
+      - name: Fail Workflow if Output is not Empty
+        if: steps.upload_results.outputs.artifact_size > 0
+        run: exit 1
